spring:
  profiles:
    active: mysql

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      passworsd: sa
      driver-class-name: org.h2.Driver
  batch:
    initialize-schema: always
    job:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/springbatch?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
#    auto ddl
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  batch:
    initialize-schema: always
#    job:
#      names: ${job.name:NONE}
---
s